# Generated by Django 4.1.7 on 2023-04-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_app', '0002_canadian_user_city_user_snack_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('canadian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_app.canadian')),
            ],
        ),
    ]
