# Generated by Django 4.1.7 on 2023-04-26 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary_app', '0004_canadian_cities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='description',
            new_name='about',
        ),
    ]
