# Generated by Django 4.1.7 on 2023-04-27 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_app', '0005_rename_description_snack_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_app.city')),
            ],
        ),
    ]
