# Generated by Django 4.1.7 on 2023-04-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_app', '0006_cityphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnackPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_app.snack')),
            ],
        ),
    ]
