# Generated by Django 4.1.7 on 2023-04-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_app', '0007_snackphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='canadian',
            name='snacks',
            field=models.ManyToManyField(to='primary_app.snack'),
        ),
    ]
